import React, { useState, useMemo } from 'react';
import { ICONS } from '../constants';
import { Transaction } from '../types';

interface PaymentModalProps {
  total: number;
  subtotal: number;
  tax: number;
  onClose: () => void;
  onConfirmPayment: (method: Transaction['paymentMethod']) => void;
  initialMethod: Transaction['paymentMethod'] | null;
}

const PaymentModal: React.FC<PaymentModalProps> = ({ total, subtotal, tax, onClose, onConfirmPayment, initialMethod }) => {
  const [step, setStep] = useState<'select' | 'cash' | 'pix'>(() => {
    if (initialMethod === 'Dinheiro') return 'cash';
    if (initialMethod === 'PIX') return 'pix';
    return 'select';
  });
  const [cashReceived, setCashReceived] = useState('');
  
  // State for PIX QR Code
  const [showQRCode, setShowQRCode] = useState(false);
  const [pixCode, setPixCode] = useState('');
  const [qrCodeUrl, setQrCodeUrl] = useState('');
  const [copied, setCopied] = useState(false);


  const handleCashPayment = () => {
    const received = parseFloat(cashReceived) || 0;
    if (received >= total) {
      onConfirmPayment('Dinheiro');
    } else {
      alert('Valor recebido é menor que o total da compra.');
    }
  };
  
  const receivedAmount = parseFloat(cashReceived) || 0;
  const change = useMemo(() => {
    if (receivedAmount > 0 && receivedAmount >= total) {
      return receivedAmount - total;
    }
    return 0;
  }, [cashReceived, total, receivedAmount]);
  
  const handleGenerateQRCode = () => {
    // In a real application, this would be generated by a payment provider API
    const mockPixPayload = `00020126580014br.gov.bcb.pix0136123e4567-e12b-12d1-a456-4266554400005303986540${total.toFixed(2).replace('.', '')}5802BR5913SupermarketPro6009SAO PAULO62070503***6304ABCD`;
    const encodedPayload = encodeURIComponent(mockPixPayload);

    setPixCode(mockPixPayload);
    setQrCodeUrl(`https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodedPayload}&qzone=1`);
    setShowQRCode(true);
  };
  
  const handleCopyCode = () => {
    if (pixCode) {
      navigator.clipboard.writeText(pixCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };


  const formatCurrency = (value: number) => `R$ ${value.toFixed(2).replace('.', ',')}`;

  const renderSelectStep = () => (
    <div className="space-y-4">
      <button 
        onClick={() => setStep('cash')}
        className="w-full bg-primary-blue text-white py-3 rounded-lg text-lg font-bold hover:bg-blue-700 transition"
      >
        PAGAR COM DINHEIRO - F1
      </button>
      <button 
        onClick={() => setStep('pix')}
        className="w-full bg-primary-blue text-white py-3 rounded-lg text-lg font-bold hover:bg-blue-700 transition"
      >
        PAGAR COM PIX - F3
      </button>
    </div>
  );

  const renderCashStep = () => (
    <div>
        <div className="mb-4">
            <label htmlFor="cashReceived" className="block text-sm font-medium text-gray-700 mb-1 text-center">
                Valor Recebido
            </label>
            <input
                type="number"
                id="cashReceived"
                name="cashReceived"
                value={cashReceived}
                onChange={(e) => setCashReceived(e.target.value)}
                step="0.01"
                min={total.toFixed(2)}
                className="w-full text-4xl font-bold text-center p-2 border-b-2 border-gray-300 focus:outline-none focus:ring-0 focus:border-primary-blue"
                required
                autoFocus
                placeholder='0,00'
            />
        </div>

        {receivedAmount > 0 && (
            <div className="my-6 text-center">
                <p className="text-lg text-gray-500">Troco</p>
                <p className="text-5xl font-extrabold text-green-600">{formatCurrency(change)}</p>
            </div>
        )}

        <div className="space-y-4 mt-8">
            <button 
                onClick={handleCashPayment} 
                className="w-full bg-green-600 text-white py-3 rounded-lg text-lg font-bold hover:bg-green-700 transition disabled:bg-gray-400"
                disabled={receivedAmount < total}
            >
                Confirmar Pagamento
            </button>
            <button 
                onClick={initialMethod ? onClose : () => { setStep('select'); setCashReceived(''); }}
                className="w-full bg-gray-200 text-gray-800 py-2 rounded-lg text-md font-semibold hover:bg-gray-300 transition"
            >
                {initialMethod ? 'Cancelar' : 'Voltar'}
            </button>
        </div>
    </div>
  );

  const renderPixStep = () => {
    if (showQRCode) {
      return (
        <div className="text-center">
          <p className="font-semibold text-gray-700">Aponte a câmera do celular para o QR Code</p>
          <div className="flex justify-center my-4">
            {qrCodeUrl ? (
                <img src={qrCodeUrl} alt="PIX QR Code" className="w-56 h-56 rounded-lg border-4 border-gray-200"/>
            ) : (
                <div className="w-56 h-56 bg-gray-100 flex items-center justify-center rounded-lg">
                    <p className="text-gray-500">Gerando QR Code...</p>
                </div>
            )}
          </div>
           <div className="space-y-2">
            <label className="text-sm font-medium text-gray-700">Ou use o PIX Copia e Cola:</label>
            <div className="flex">
                <input
                    type="text"
                    readOnly
                    value={pixCode}
                    className="w-full bg-gray-100 text-gray-600 text-xs px-2 py-2 border border-gray-300 rounded-l-md"
                />
                <button
                    onClick={handleCopyCode}
                    className="bg-gray-200 text-gray-800 px-3 py-2 rounded-r-md hover:bg-gray-300 text-sm font-semibold"
                >
                    {copied ? 'Copiado!' : 'Copiar'}
                </button>
            </div>
          </div>
          <div className="mt-6 space-y-2">
            <button
              onClick={() => onConfirmPayment('PIX')}
              className="w-full bg-green-600 text-white py-3 rounded-lg text-lg font-bold hover:bg-green-700 transition"
            >
              Confirmar Pagamento
            </button>
            <button
              onClick={() => setShowQRCode(false)}
              className="w-full bg-gray-200 text-gray-800 py-2 rounded-lg text-md font-semibold hover:bg-gray-300 transition"
            >
              Voltar
            </button>
          </div>
        </div>
      );
    }

    return (
      <div className="space-y-4">
        <button
          onClick={() => onConfirmPayment('PIX')}
          className="w-full bg-green-600 text-white py-3 rounded-lg text-lg font-bold hover:bg-green-700 transition"
        >
          Confirmar Pagamento com PIX
        </button>
        <button
            onClick={handleGenerateQRCode}
            className="w-full bg-blue-500 text-white py-3 rounded-lg text-lg font-bold hover:bg-blue-600 transition"
        >
            Gerar QR Code para Cliente
        </button>
        <button
          onClick={initialMethod ? onClose : () => setStep('select')}
          className="w-full bg-gray-200 text-gray-800 py-2 rounded-lg text-md font-semibold hover:bg-gray-300 transition"
        >
          {initialMethod ? 'Cancelar' : 'Voltar'}
        </button>
      </div>
    );
  };

  const renderContent = () => {
    switch (step) {
      case 'cash':
        return renderCashStep();
      case 'pix':
        return renderPixStep();
      case 'select':
      default:
        return renderSelectStep();
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-60 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg shadow-2xl p-8 w-full max-w-md m-4 transform transition-all">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-2xl font-bold text-gray-800">Confirmar Pagamento</h2>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 transition">
            {ICONS.x}
          </button>
        </div>

        <div className="my-6 space-y-2 border-y py-4">
            <div className="flex justify-between text-gray-600">
              <span>Subtotal</span>
              <span>{formatCurrency(subtotal)}</span>
            </div>
             <div className="flex justify-between text-gray-600">
              <span>Impostos</span>
              <span>{formatCurrency(tax)}</span>
            </div>
        </div>
        
        <div className="text-center my-6">
          <p className="text-lg text-gray-500">Total a Pagar</p>
          <p className="text-5xl font-extrabold text-primary-blue">{formatCurrency(total)}</p>
        </div>

        {renderContent()}
      </div>
    </div>
  );
};

export default PaymentModal;